kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeUpdateView,
    DishTypeCreateView,
    DishTypeDeleteView,
    IngredientListView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path("dish_types/", DishTypeListView.as_view(), name="dish-type-list"),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish_types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
    path(
        "ingredients/",
        IngredientListView.as_view(),
        name="ingredient-list"
    ),
    path(
        "ingredients/create/",
        IngredientCreateView.as_view(),
        name="ingredient-create"
    ),
    path(
        "ingredients/<int:pk>/update/",
        IngredientUpdateView.as_view(),
        name="ingredient-update"
    ),
    path(
        "ingredients/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete"
    ),
]

app_name = "kitchen"

kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("kitchen.urls", namespace="kitchen")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/navbar.html
<div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur border-radius-xl top-0 z-index-fixed shadow position-absolute my-3 p-2 start-0 end-0 mx-4">
          <div class="container-fluid px-0">
             <a class="navbar-brand font-weight-bolder ms-sm-3 text-sm" href="{{ user.get_absolute_url }}" rel="tooltip" title="Detail" data-placement="bottom" >
              User: {{ user.get_username }}
             </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-auto о">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex cursor-pointer align-items-center font-weight-semibold" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="material-symbols-rounded opacity-6 me-2 text-md">dashboard</i>
                    Pages
                    <img src="../../../static/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                    <div class="d-none d-lg-block">
                      <a href="{% url 'kitchen:index' %}" class="dropdown-item border-radius-md">
                        <span>Home</span>
                      </a>
                      <a href="{% url 'kitchen:cook-list' %}" class="dropdown-item border-radius-md">
                        <span>Cooks</span>
                      </a>
                      <a href="{% url 'kitchen:dish-list' %}" class="dropdown-item border-radius-md">
                        <span>Dishes</span>
                      </a>
                      <a href="{% url 'kitchen:dish-type-list' %}" class="dropdown-item border-radius-md">
                        <span>Dishes Type</span>
                      </a>
                      <a href="{% url 'kitchen:ingredient-list' %}" class="dropdown-item border-radius-md">
                        <span>Ingredients</span>
                      </a>
                    </div>
                    <div class="d-lg-none">
                      <a href="{% url 'kitchen:index' %}" class="dropdown-item border-radius-md">
                        <span>Home</span>
                      </a>
                      <a href="{% url 'kitchen:cook-list' %}" class="dropdown-item border-radius-md">
                        <span>Cooks</span>
                      </a>
                      <a href="{% url 'kitchen:dish-list' %}" class="dropdown-item border-radius-md">
                        <span>Dishes</span>
                      </a>
                      <a href="{% url 'kitchen:dish-type-list' %}" class="dropdown-item border-radius-md">
                        <span>Dishes Type</span>
                      </a>
                      <a href="{% url 'kitchen:ingredient-list' %}" class="dropdown-item border-radius-md">
                        <span>Ingredients</span>
                      </a>
                    </div>
                  </div>
                </li>

                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="https://github.com/oleg-gj/Service-for-the-restaurant-kitchen" target="_blank">
                    <i class="fa fa-github me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-semibold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Star me on Github">Github</p>
                  </a>
                </li>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <form action="{% url 'logout' %}" method="post" class="nav-item my-auto ms-3 ms-lg-0">
                    {% csrf_token %}
                    <button type="submit" class="btn  bg-gradient-dark  mb-0 mt-2 mt-md-0">Logout</button>
                  </form>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination pagination-dark">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">&laquo;</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link bigsection">{{ page_obj.number }}/{{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
      </li>
    {% endif %}
  </ul>
{% endif %}