kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeUpdateView,
    DishTypeCreateView,
    DishTypeDeleteView,
    IngredientListView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path("dish_types/", DishTypeListView.as_view(), name="dish-type-list"),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish_types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
    path(
        "ingredients/",
        IngredientListView.as_view(),
        name="ingredient-list"
    ),
    path(
        "ingredients/create/",
        IngredientCreateView.as_view(),
        name="ingredient-create"
    ),
    path(
        "ingredients/<int:pk>/update/",
        IngredientUpdateView.as_view(),
        name="ingredient-update"
    ),
    path(
        "ingredients/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete"
    ),
]

app_name = "kitchen"

kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("kitchen.urls", namespace="kitchen")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Dish(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    dish_type = models.ForeignKey(
        "DishType",
        related_name="dishes",
        on_delete=models.CASCADE
    )
    cooks = models.ManyToManyField("Cook", related_name="dishes")
    ingredients = models.ManyToManyField("Ingredient", related_name="dishes")

    def __str__(self):
        return self.name


class DishType(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=100, unique=True)
    caloric_content = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    year_of_experience = models.IntegerField(default=0)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model

from kitchen.models import Ingredient, Dish


class SearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Dish
        fields = "__all__"

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.models import Cook, Dish, DishType, Ingredient
from kitchen.forms import CookSearchForm, SearchForm, DishForm


@login_required
def index(request):
    """View function for the home page of the site."""
    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dishes_type = DishType.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dishes_type": num_dishes_type,
        "num_visits": num_visits + 1,
    }

    return render(request, "kitchen/index.html", context=context)


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    queryset = Cook.objects.all()
    paginate_by = 5

    def get_queryset(self):
        username = self.request.GET.get("username")

        if username:
            return self.queryset.filter(username__icontains=username)

        return self.queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = CookSearchForm(initial={"username": username})
        return context


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    fields = "__all__"
    success_url = reverse_lazy("kitchen:cook-list")
    template_name = "kitchen/cook_form.html"


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    fields = "__all__"
    success_url = reverse_lazy("kitchen:cook-list")
    template_name = "kitchen/cook_form.html"


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    template_name = "kitchen/cook_delete.html"
    success_url = reverse_lazy("kitchen:cook-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    queryset = Dish.objects.all()
    paginate_by = 5

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return self.queryset.filter(name__icontains=name)
        return self.queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = SearchForm(initial={"name": name})
        return context


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    queryset = (
        Dish.objects.prefetch_related("cooks").select_related("dish_type")
    )


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")
    template_name = "kitchen/dish_form.html"
    form_class = DishForm


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")
    template_name = "kitchen/dish_form.html"
    form_class = DishForm


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    template_name = "kitchen/dish_delete.html"
    success_url = reverse_lazy("kitchen:dish-list")


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    queryset = DishType.objects.all()
    template_name = "kitchen/dish_type_list.html"
    paginate_by = 5

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return self.queryset.filter(name__icontains=name)
        return self.queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = SearchForm(initial={"name": name})
        return context


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen/dish_type_delete.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    queryset = Ingredient.objects.all()
    paginate_by = 5

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return self.queryset.filter(name__icontains=name)
        return self.queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IngredientListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = SearchForm(initial={"name": name})
        return context


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("kitchen:ingredient-list")
    template_name = "kitchen/ingredient_form.html"


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("kitchen:ingredient-list")
    template_name = "kitchen/ingredient_form.html"


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    template_name = "kitchen/ingredient_delete.html"
    success_url = reverse_lazy("kitchen:ingredient-list")

templates/kitchen/cook_delete.html
{% extends "base.html" %}

{% block page_description %}
  <h1 class="text-white font-weight-black pt-3 mt-n5">Delete cook</h1>
{% endblock %}


{% block content %}
  <div class="ms-auto text-center">
    <h4>Are you sure you want to delete the cook <strong>{{ cook }}</strong>?</h4>
    <form method="post">
      <a class="btn btn-danger" href="{% url 'kitchen:cook-detail' pk=cook.id %}">Cancel</a>
      {% csrf_token %}
      <input class="btn btn-dark" type="submit" value="Yes, delete">
    </form>
  </div>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block page_description %}
  <h1 class="text-white font-weight-black pt-3 mt-n5">Cook detail</h1>
  <p class="lead text-white mt-3">On this page you can se detail description about cook</p>
{% endblock %}

{% block content %}
  <div class="ms-auto row">
    <div class="ms-auto text-start col">
      <h2>Username: <strong>{{ cook.username }}</strong></h2>
    </div>
    <div class="text-end col">
      <a class="btn btn-dark"
         href="{% url 'kitchen:cook-update' pk=cook.id %}">Update</a>
      <a class="btn btn-danger"
         href="{% url 'kitchen:cook-delete' pk=cook.id %}">Delete</a>
    </div>
  </div>

  <p><strong>First name:</strong> {{ cook.first_name }}</p>
  <p><strong>Last name:</strong> {{ cook.last_name }}</p>
  <p><strong>Experience:</strong> {{ cook.year_of_experience }}</p>
  <p><strong>Is staff:</strong> {{ cook.is_staff }}</p>

  <div>
    <h4>Dishes: </h4>
    {% for dish in cook.dishes.all %}
      <hr>
      <p><strong>Name:</strong> {{ dish.name }}</p>
      <p><strong>Description:</strong> {{ dish.description }}</p>
      <p><strong>Price:</strong> {{ dish.price }}</p>

    {% empty %}
      <p>No dishes!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block page_description %}
  {% if cook %}
    <h1 class="text-white font-weight-black pt-3 mt-n5">Update</h1>
    <p class="lead text-white mt-3">On this page you can update new cook</p>
  {% else %}
    <h1 class="text-white font-weight-black pt-3 mt-n5">Create</h1>
    <p class="lead text-white mt-3">On this page you can create new cook</p>
  {% endif %}
{% endblock %}


{% block content %}
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-dark" type="submit" value="Submit">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block page_description %}
  <h1 class="text-white font-weight-black pt-3 mt-n5">Cooks</h1>
  <p class="lead text-white mt-3">On this page you can see all cooks in you restaurant</p>
{% endblock %}

{% block content %}
  <div class="ms-auto row">
    <div class="ms-auto text-start col-4">
        <form class=" ms-auto row" action="" method="get">
          <div class="col">{{ search_form|crispy }}</div>
          <input class="col btn btn-light" type="submit" value="Search">
        </form>
    </div>
    <div class="text-end col">
      <a href="{% url 'kitchen:cook-create' %}"
         class="btn btn-dark link-to-page">Create
      </a>
    </div>
  </div>

      <div class="section text-center table-responsive">

          {% if cook_list %}
          <table class="table">
          <thead>
            <tr>
              <th scope="col"><h5>ID</h5></th>
              <th scope="col"><h5>Username</h5></th>
              <th scope="col"><h5>First name</h5></th>
              <th scope="col"><h5>Last name</h5></th>
              <th scope="col"><h5>Experience</h5></th>
            </tr>
          </thead>
            {% for cook in cook_list %}
              <tbody class="table-group-divider">
              <tr>
                <th scope="row">{{ cook.id }}</th>
                <th scope="row">
                  <a href="{% url 'kitchen:cook-detail' pk=cook.id %}" title="Detail">
                    {{ cook.username }}
                  </a>
                </th>
                <th scope="row">{{ cook.first_name }}</th>
                <th scope="row">{{ cook.last_name }}</th>
                <th scope="row">{{ cook.year_of_experience }}</th>
              </tr>
              </tbody>
            {% endfor %}
          </table>
        {% else %}
          <p>There are no cooks in the service.</p>
        {% endif %}
      </div>

{% endblock %}

templates/kitchen/dish_delete.html
{% extends "base.html" %}

{% block page_description %}
  <h1 class="text-white font-weight-black pt-3 mt-n5">Delete dish</h1>
{% endblock %}


{% block content %}
  <div class="ms-auto text-center">
    <h4>Are you sure you want to delete the dish <strong>{{ dish }}</strong>?</h4>
    <form method="post">
      <a class="btn btn-danger" href="{% url 'kitchen:dish-list' %}">Cancel</a>
      {% csrf_token %}
      <input class="btn btn-dark" type="submit" value="Yes, delete">
    </form>
  </div>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}

{% block page_description %}
  <h1 class="text-white font-weight-black pt-3 mt-n5">Dish detail</h1>
  <p class="lead text-white mt-3">On this page you can se detail description about dish</p>
{% endblock %}

{% block content %}
  <div class="ms-auto row">
    <div class="ms-auto text-start col">
      <h2>Dish: <strong>{{ dish.name }}</strong></h2>
    </div>
    <div class="text-end col">
      <a class="btn btn-dark"
         href="{% url 'kitchen:dish-update' pk=dish.id %}">Update</a>
    </div>
  </div>

<p><strong>Price:</strong> {{ dish.price }}</p>
<p><strong>Dish Type:</strong> {{ dish.dish_type }}</p>
<p><strong>Cooks:</strong></p>
  {% for cook in dish.cooks.all %}
    <li>{{ cook }}</li>
  {% empty %}
    <p>No cooks!</p>
  {% endfor %}
  <br>
<p><strong>Description:</strong> {{ dish.description }}</p>

<div>
  <h3>Ingredients:</h3>
  {% for ingredient in dish.ingredients.all %}
    <li>{{ ingredient}}</li>

  {% empty %}
    <p>No ingredients!</p>
  {% endfor %}
</div>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block page_description %}
  {% if dish %}
    <h1 class="text-white font-weight-black pt-3 mt-n5">Update</h1>
    <p class="lead text-white mt-3">On this page you can update new dish</p>
  {% else %}
    <h1 class="text-white font-weight-black pt-3 mt-n5">Create</h1>
    <p class="lead text-white mt-3">On this page you can create new dish</p>
  {% endif %}
{% endblock %}

{% block content %}

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}

  <input class="btn btn-dark" type="submit" value="Submit">
</form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block page_description %}
  <h1 class="text-white font-weight-black pt-3 mt-n5">Dishes</h1>
  <p class="lead text-white mt-3">On this page you can see all dishes in you restaurant</p>
{% endblock %}

{% block content %}
  <div class="ms-auto row">
    <div class="ms-auto text-start col-4">
        <form class="row" action="" method="get">
          <div class="col">{{ search_form|crispy }}</div>
          <input class="col btn btn-light" type="submit" value="Search">
        </form>
    </div>
    <div class="text-end col">
      <a href="{% url 'kitchen:dish-create' %}"
         class="btn btn-dark link-to-page">Create
      </a>
    </div>
  </div>

      <div class="section text-center table-responsive">
        {% if dish_list %}
          <table class="table">
            <thead>
            <tr>
              <th scope="col"><h5>ID</h5></th>
              <th scope="col"><h5>Name</h5></th>
              <th scope="col"><h5>Price</h5></th>
              <th scope="col"><h5>Update</h5></th>
              <th scope="col"><h5>Delete</h5></th>
            </tr>
            </thead>

            {% for dish in dish_list %}
              <tr>
                <th scope="row">
                  {{ dish.id }}
                </th>
                <th scope="row">
                  <a href="{% url 'kitchen:dish-detail' pk=dish.id %}">
                  {{ dish.name }}
                  </a>
                </th>
                <th scope="row">
                  {{ dish.price }}
                </th>
                <th scope="row">
                  <a href="{% url 'kitchen:dish-update' pk=dish.id %}">Update</a>
                </th>
                <th scope="row">
                  <a class="link-danger"
                     href="{% url 'kitchen:dish-delete' pk=dish.id %}">Delete</a>
                </th>
              </tr>
            {% endfor %}
          </table>

        {% else %}
          <p>There are no dishes in the service.</p>
        {% endif %}
      </div>
{% endblock %}

templates/kitchen/dish_type_delete.html
{% extends "base.html" %}

{% block page_description %}
  <h1 class="text-white font-weight-black pt-3 mt-n5">Delete dish type</h1>
{% endblock %}

{% block content %}
  <div class="ms-auto text-center">
    <h4>Are you sure you want to delete the dish type <strong>{{ dishtype }}</strong>?</h4>
    <form method="post">
      <a class="btn btn-danger" href="{% url 'kitchen:dish-type-list' %}">Cancel</a>
      {% csrf_token %}
      <input class="btn btn-dark" type="submit" value="Yes, delete">
    </form>
  </div>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "base.html" %}

{% block page_description %}
  {% if dishtype %}
    <h1 class="text-white font-weight-black pt-3 mt-n5">Update</h1>
    <p class="lead text-white mt-3">On this page you can update new dish type</p>
  {% else %}
    <h1 class="text-white font-weight-black pt-3 mt-n5">Create</h1>
    <p class="lead text-white mt-3">On this page you can create new dish type</p>
  {% endif %}
{% endblock %}

{% block content %}
<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form }}

  <input class="btn btn-dark" type="submit" value="Submit">
</form>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block page_description %}
  <h1 class="text-white font-weight-black pt-3 mt-n5">Dishes Type</h1>
  <p class="lead text-white mt-3">On this page you can see all dishes type in
    you restaurant</p>
{% endblock %}

{% block content %}
  <div class="ms-auto row">
    <div class="ms-auto text-start col-4">
        <form class="row" action="" method="get">
          <div class="col">{{ search_form|crispy }}</div>
          <input class="col btn btn-light" type="submit" value="Search">
        </form>
    </div>
    <div class="text-end col">
      <a href="{% url 'kitchen:dish-type-create' %}"
         class="btn btn-dark link-to-page">Create
      </a>
    </div>
  </div>

  <div class="section text-center table-responsive">
    {% if dishtype_list %}
      <table class="table">
        <tr>
          <th scope="col"><h5>ID</h5></th>
          <th scope="col"><h5>Name</h5></th>
          <th scope="col"><h5>Update</h5></th>
          <th scope="col"><h5>Delete</h5></th>
        </tr>

        {% for dish in dishtype_list %}
          <tr>
            <th scope="row">
              {{ dish.id }}
            </th>
            <th scope="row">
              {{ dish.name }}
            </th>
            <th scope="row">
              <a href="{% url 'kitchen:dish-type-update' pk=dish.id %}">Update</a>
            </th>
            <th scope="row">
              <a class="link-danger"
                 href="{% url 'kitchen:dish-type-delete' pk=dish.id %}">Delete</a>
            </th>
          </tr>
        {% endfor %}
      </table>

    {% else %}
      <p>There are no dish type in the service.</p>
    {% endif %}
  </div>
{% endblock %}

templates/kitchen/ingredient_delete.html
{% extends "base.html" %}

{% block page_description %}
  <h1 class="text-white font-weight-black pt-3 mt-n5">Delete ingredient</h1>
{% endblock %}


{% block content %}
  <div class="ms-auto text-center">
    <h4>Are you sure you want to delete the ingredient <strong>{{ ingredient }}</strong>?</h4>
    <form method="post">
      <a class="btn btn-danger" href="{% url 'kitchen:ingredient-list' %}">Cancel</a>
      {% csrf_token %}
      <input class="btn btn-dark" type="submit" value="Yes, delete">
    </form>
  </div>
{% endblock %}

templates/kitchen/ingredient_form.html
{% extends "base.html" %}

{% block page_description %}
  {% if ingredient %}
    <h1 class="text-white font-weight-black pt-3 mt-n5">Update</h1>
    <p class="lead text-white mt-3">On this page you can update new ingredient</p>
  {% else %}
    <h1 class="text-white font-weight-black pt-3 mt-n5">Create</h1>
    <p class="lead text-white mt-3">On this page you can create new ingredient</p>
  {% endif %}
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form }}
<button type="submit" class="btn btn-dark">Submit</button>
</form>
{% endblock %}

templates/kitchen/ingredient_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block page_description %}
  <h1 class="text-white font-weight-black pt-3 mt-n5">Ingredients</h1>
  <p class="lead text-white mt-3">On this page you can see all ingredients in you restaurant.</p>
{% endblock %}

{% block content %}
      <div class="ms-auto row">
    <div class="ms-auto text-start col-4">
        <form class="row" action="" method="get">
          <div class="col">{{ search_form|crispy }}</div>
          <input class="col btn btn-light" type="submit" value="Search">
        </form>
    </div>
    <div class="text-end col">
      <a href="{% url 'kitchen:ingredient-create' %}"
         class="btn btn-dark link-to-page">Create
      </a>
    </div>
  </div>

      <div class="section text-center table-responsive">

        {% if ingredient_list %}
          <table class="table">
            <tr>
              <th scope="col"><h5>ID</h5></th>
              <th scope="col"><h5>Name</h5></th>
              <th scope="col"><h5>Calories</h5></th>
              <th scope="col"><h5>Update</h5></th>
              <th scope="col"><h5>Delete</h5></th>
            </tr>

            {% for ingredient in ingredient_list %}
              <tr>
                <th scope="row">
                  {{ ingredient.id }}
                </th>
                <th scope="row">
                  {{ ingredient.name }}
                </th>
                <th scope="row">
                  {{ ingredient.caloric_content }}
                </th>
                <th scope="row">
                  <a href="{% url 'kitchen:ingredient-update' pk=ingredient.id %}">Update</a>
                </th>
                <th scope="row">
                  <a class="link-danger" href="{% url 'kitchen:ingredient-delete' pk=ingredient.id %}">Delete</a>
                </th>
              </tr>
            {% endfor %}
          </table>

        {% else %}
          <p>There are no dishes in the service.</p>
        {% endif %}
      </div>
{% endblock %}